### ISSUE TITLE
mob_stats breaks when group_var is not a factor

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#102]
This is because of this [line](https://github.com/MoBiodiv/mobr/blob/master/R/mobr_boxplots.R#L101) which assumes that `group` is a factor. We need a more robust system because `group` could be a `character` or a `numeric` class of variable.

**Comment by FelixMay** [comment]
I started debugging the mob_stats function. During that I noticed that in the example data set `inv_comm` there are sites with one or even zero individuals. In this case of course rarefaction does not show any interesting results. 
Any ideas how to deal with this issue? Only in this function by selecting a certain minimum number of individuals or is this relevant also for other functions?

**Comment by FelixMay** [comment]
And a second questions on revision of this function (mob_stats) what about the extrapolated richness using SpadeR::ChaoSpecies? Should I reintroduce that or does that cause problems because of package dependencies? What about using vegan::estimateR ?
