### ISSUE TITLE
cleanup boxplot functions?

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#104]
It would be nice if the three boxplot functions can be combined into one, which allows the users to specify whether it's sample, group or betaPIE.

**Comment by rueuntal** [comment]
I'm also wondering if it would be better to use violin plots instead of boxplots (or make that an option), which gives a more complete representation of data. This is not a priority though.

**Comment by dmcglinn** [comment]
Something like this is probably the best option if we decide we want to implement these at least as an option.
```r
library(ggplot2)
data(inv_comm)
data(inv_plot_attr)
inv_mob_in = make_mob_in(inv_comm, inv_plot_attr)
inv_stats = get_mob_stats(inv_mob_in, 'group', nperm=100)
p = ggplot(inv_stats$samples, aes(x=group, y=PIE)) + geom_violin(trim=F)
p
```
The other package for making these `vioplot` is really pretty dumb in my opinion

**Comment by rueuntal** [comment]
Seems that we've already got a good hang of the boxplots and violin plots are not a priority at the moment.
