### ISSUE TITLE
plot_samples error

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#105]
The following code generates an error with a fresh install of our package
```r
library(mobr)
data(inv_comm)
data(inv_plot_attr)
inv_mob_in = make_mob_in(inv_comm, inv_plot_attr)
stats = mob_stats(inv_mob_in)
plot_samples(stats)
Error in eval(expr, envir, enclos) : object 'S' not found
In addition: Warning message:
In (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  row names were found from a short variable and have been discarded
```

**Comment by rueuntal** [comment]
Thanks for checking @dmcglinn ! I got the same error. The following runs but returns the weird graphs that I showed you: 
```
plot_samples(stats$samples, tukey = T)
```

**Comment by dmcglinn** [comment]
Did something change with the mob_in class of object that can explain this? Probably debugging is only way to figure it out.

Dan

**Comment by FelixMay** [comment]
Hi @rueuntal and @dmcglinn, thanks for the hints. I will debug the mob_stats and boxplots function soon, but I think I will only manage next week. But for sure before your writing retreat!

**Comment by FelixMay** [comment]
Hi @rueuntal  and @dmcglinn, this was an easy one. It is not really a bud, more the question how the function is called. The plotting function needs to be called on the item `stats$samples`.

```r
library(mobr)
data(inv_comm)
data(inv_plot_attr)
inv_mob_in = make_mob_in(inv_comm, inv_plot_attr)
stats = mob_stats(inv_mob_in)
plot_samples(stats$samples)
```

It works this way, but I am not sure it is optimal. I suggest we first discuss how the boxplot function should look like and then I implement in the way we would like to have it. 

Just sent me your wishlist from the meeting :o) (Christmas is close)
