### ISSUE TITLE
spatial rarefaction function miscalculating richness for n=1

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#115]
It appears that our function `rarefaction` is miscalculating the richness when sample size is 1 (possibly at other sizes as well I'm not sure yet). Was this function ever compared to hand-worked examples as a test? We should get some explicit tests in place for this function. Here is code to demonstrate the bug: 

```r

# create a 3 species community distributed across 4 sites
comm = rbind(c(0, 0, 1), 
                       c(0, 0, 0),
                       c(0, 1, 0), 
                       c(1, 0, 0))
replicate(4, rarefaction(comm, 'spat', xy_coords = 1:4))
# note that the replicates differ from on another the correct value when 
# n = 1 is 0.75 (= mean(c(1, 0, 1, 1)) the site richness values)
# but sometimes the function returns 1. 
```

I think this bug likely has something to do with the reordering of the data prior to computing the accumulation curves to try to randomize the pattern by which ties are encountered.

**Comment by rueuntal** [comment]
oh no！ that sounds bad. I'm currently at IBS but will try to look into it
tonight.

**Comment by dmcglinn** [comment]
It does appear to be because of the reordering b/c I changed this part of the rarefaction function and it returned the correct answer: 

```
# I changed this old line in the function rarefaction
new_order = sample(1:n)
# to this so that the shuffled order stopped
new_order = 1:n 
```

**Comment by rueuntal** [comment]
OK is my input still needed?

I guess we'd need to rerun the sensitivity analysis, right?

**Comment by dmcglinn** [comment]
I found the bug, I'm going to submit a PR for this in a few minutes.

**Comment by dmcglinn** [comment]
I think so on the sensitivity analyses let me first make sure this updated version matches some simple by hand examples to make sure there are no other bugs.

**Comment by rueuntal** [comment]
sounds great thanks Dan！
