### ISSUE TITLE
rarefied richness analysis for boxplots can fail

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#118]
The rarefied richness analysis that @FelixMay implemented can fail when a treatment has a strong influence on abundance such that all the plots of a given treatment fall below the 10 individual cutoff (this occurred in the glade ants 2011 analysis). The analysis will return an error like this:

```
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```
which results because any sample with less than 10 individuals was dropped effectively making it a single treatment analysis. Although this is likely pretty rare we should add some code to catch this error and then remove the rarefaction analysis from the suite of tests.

**Comment by rueuntal** [comment]
Should be fixed in #131 .
