### ISSUE TITLE
Issues from Shane Blowes <sablowes@gmail.com>

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#120]
Hi Dan and Xiao

I’m continuing the use the mobr package as it develops…thanks for the great resource.

Couple of (simple) things have popped up in the new version that I want to bring to your attention:
        - typo in stack_effects(). The ‘label_indv’ argument should be ‘label_indiv’
        - something funky happens with the plot.mob_out function for my data that results in the the individual based rarefaction curves being mislabelled. Specifically, the column order of my groups in the mob_out$indiv_rare is: ‘sample’, ‘fished’, ‘protected’. But as I call set trt_group=‘protected’, the code as currently written mixes up the two curves. I suspect, but don’t know, that this is going to be a problem for any data sets where the alphabetical order of the grouping variable is not the same as the order of the treatment/reference groups?

Finally, my results sometimes have NAs in the mob_out$N part of the object returned by the get_delta_stats() function. I’m still trying to figure out why…

Cheers,
Shane

**Comment by rueuntal** [comment]
Hi Dan - Do you know if these have been resolved? If not we probably want to reach to Shane and ask for his data for some debugging.

**Comment by rueuntal** [comment]
Should be fixed in #136 .
