### ISSUE TITLE
effort > N in rarefaction

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#122]
Right now it seems that `rarefaction()` throws a warning when `effort` > total abundance `N` and gives back `S_obs`. We've probably talked about this before - is there a reason why it doesn't return `NA` instead?

**Comment by dmcglinn** [comment]
I think this is historical because a lot of the structure of `rarefaction` was inherited from `vegan::rarefy` if you would prefer NA's then that would be easy to implement. In what context would you like to be able to supply `effort` > `N`. Also do you think the warning is still useful in these contexts?

**Comment by dmcglinn** [comment]
I think this is due to historical reasons as our function was adapted from `vegan::rarefy`. I don't have a strong feeling either way. If we did switch to returning `NA` do you think the warning message should still be issued? Under what part of the analysis does this come up - density effects?

**Comment by rueuntal** [comment]
I think in our current implementation it only occurs in the rescaling — by
stretching the axis we might be making inference at abundance values
outside of the observed range. I did an ad hoc fix in rescale_rarefaction,
where the extrapolated values are removed from effort.

**Comment by dmcglinn** [comment]
ok I'll take a look and let you know what seems like the best solution to me.

**Comment by rueuntal** [comment]
OK thanks!

**Comment by dmcglinn** [comment]
In ae0d3fa19a03a48876953234ac647728e290314c it looks like I decided to return the observed S when effort > n for individual-based rarefaction unless the argument `extrapolate` is set to `TRUE` in which case the returned value is extrapolated using Chao 1.
