### ISSUE TITLE
log gamma warnings 

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#124]
Using the analytical rescaling of the rarefaction as introduced in #123 sometimes results in warnings about the input of `lgamma` being out of range. 

I looked at a plot of the `lgamma` function and it shows this bizarre pattern. 

![image](https://cloud.githubusercontent.com/assets/1190381/22378296/265268b0-e483-11e6-96de-d674c8594ac9.png)

So it is undefined for certain bands of negative numbers. Based on your derivation would you ever expect `lgamma` to be computed on a negative quantity. If not then I can setup an if statement so it is not evaluated for negative values at all.

**Comment by rueuntal** [comment]
I probably won't be able to look into this until next week but I think that's exactly what it is - `lgamma` returns -inf for negative values and throws a warning. Another small annoyance is that it doesn't take multiple TRUE/FALSE argument like lchoose, in `ifelse`.

**Comment by dmcglinn** [comment]
I looked into this more and the warnings are unavoidable when doing the fast lgamma calculation across the vector of species abundances so PR #125 uses the `suppressWarnings` approach.
