### ISSUE TITLE
Add argument subset to make_mob_in or get_delta_stats

### ISSUE THREAD

**Issue by nathanbaker04** [MoBiodiv/mobr#130]
This would be useful if users want to easily subset both the site x species matrix and the plot attributes matrix with a simple binary argument. The argument should be called `subset` so that it is clear what its function is.

**Comment by rueuntal** [comment]
Hi @nathanbaker04 - sorry for the very late reply. Instead of making the existing functions even more complex than they already are, I'm inclined to leave the subsetting to the users. @dmcglinn what do you think?

**Comment by dmcglinn** [comment]
The function `subset.mob_in` was added back in 9a241e7a88fa7ca that accomplishes this task
