### ISSUE TITLE
mobr  installation problem (Ubuntu 14.04)

### ISSUE THREAD

**Issue by dylancraven** [MoBiodiv/mobr#137]
When installing mobr, received this error:
configure: error: missing required header GL/glu.h

it appears to be a problem related to 'rgl', which has to be addressed by installing a couple of additional libraries in the terminal:
sudo apt-get install libglu1-mesa-dev  freeglut3-dev  mesa-common-dev
sudo apt-get install bwidget

# detailed here (#25): http://stackoverflow.com/questions/15292905/how-to-solve-the-error-missing-required-header-gl-gl-h-while-installing-the-p

**Comment by rueuntal** [comment]
@dmcglinn I'm trying to install mobr on my new mac and am getting possibly the same error. Message below:
```
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so
  Reason: image not found
ERROR: lazy loading failed for package ‘mobr’
```

**Comment by dmcglinn** [comment]
I think when we merge the latest PR this will go away

Dan

**Comment by rueuntal** [comment]
OK great!

**Comment by dmcglinn** [comment]
A quick way to check is `devtools::install_github('dmcglinn/mobr')`

**Comment by rueuntal** [comment]
Thanks @dmcglinn , I got it fixed. It was an X11 dependency on Mac.

**Comment by dmcglinn** [comment]
we have removed the dependency on `rgl`
