### ISSUE TITLE
Why did we drop rarefied S from plot.mob_stats (i.e., the boxplots)?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#139]
Does anyone remember why we did this? We still calculate it in `get_mob_stats` and carry out permutation tests on it but I think during our discussions in Boston that we decided to axe it but I can't really remember a good reason for doing this.

**Comment by rueuntal** [comment]
My recollection is that it's often not interesting at the local scale and
we'd end up losing a lot of data, while the shape of the rarefaction curve
is already captured by other quantities.

**Comment by rueuntal** [comment]
Seems that @FelixMay 's PR #146 puts rarefied S back in as an option. I'll go ahead and close this.
