### ISSUE TITLE
Plots with zero individuals included in PIE calculations

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#141]
in the function `get_mob_stats` we should not include plots with zero individuals in the treatment average. Unfortunately the zero individual plot counter is never set: 

https://github.com/MoBiodiv/mobr/blob/master/R/mobr_boxplots.R#L157

@FelixMay if you're still actively working in this section of code can you please fix this. Otherwise I can do it quickly.

**Comment by FelixMay** [comment]
Hi @dmcglinn , yes I will fix that.

**Comment by dmcglinn** [comment]
I made a mistake the problem is not that the zero plot counter is not set because it clearly is by the line I referenced. Instead the problem is that those zero plot PIE values are set to NA. What prompted my assumption that this was the problem is a downstream error from lm that there are NA's in the y value. 

```r
data(inv_comm)
data(inv_plot_attr)
inv_mob_in = make_mob_in(inv_comm, inv_plot_attr)
inv_stats = get_mob_stats(inv_mob_in, 'group', nperm=100,  n_min=5)
```
That results in the following error: 
```
 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  NA/NaN/Inf in 'y' 
```

**Comment by dmcglinn** [comment]
I'm not exactly sure where the problem is but this does not occur for a few other datasets I checked just the invasion dataset which has some of the plots with no individuals so my guess is it is somehow related.

**Comment by dmcglinn** [comment]
@FelixMay and I have decided to remove plots with one individual from the PIE calculation because ENS_PIE is undefined for a PIE of zero.
