### ISSUE TITLE
Include dependency on dplyr

### ISSUE THREAD

**Issue by FelixMay** [MoBiodiv/mobr#149]
Hi @rueuntal and @dmcglinn ,
I discussed the mob_stats and boxplots function with Shane. He convinced my that the coding of the calculations for the different indices and their bootstrap resamples is cleaner and more efficient using dplyr. How do you feel of including one extra dependency? Is that OK or should rather try to avoid additional dependencies? Would be great when you answer quickly, so that I can go on with the coding in either way.

**Comment by rueuntal** [comment]
Hi @FelixMay - Since dplyr is one of the standard data analysis libraries now, my feeling is that the extra dependency wouldn't be an issue.
