### ISSUE TITLE
rarefy_sample_explicit function

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#15]
hey @rueuntal can you explain to me what these lines of code are accomplishing:

https://github.com/MoBiodiv/mobr/blob/master/R/mobr.R#L46-L49

```
        # 1 for absence, 0 for presence
        sp_bool = as.data.frame(ifelse(sp_ordered[ , 1:ncol(sp_ordered)] == 0, 1, 0)) 
        rich = cumprod(sp_bool)
        explic_loop[ , i] = as.numeric(ncol(dat_sp) - 1 - rowSums(rich))
```
I don't understand what the variable `rich` represents? Thanks!

**Comment by rueuntal** [comment]
Yeah we are perhaps sacrificing some readability for efficiency here. This is counting the number of species in a treatment accumulating with samples (plots). The abundances are converted to 0's & 1's - 0 for PRESENCE and 1 for ABSENCE within a plot, the reverse of what we'd normally expect. Then the cumulative presence/absence (`rich` here) is obtained by taking the column product, going down one row at a time. So if one species is present in any of the rows above the focal row, we'd get a product of zero. If it's absent all the way down, we'd get a 1. Then the last line computes the richness for 1 plot, 2 plots, ... (the `rowSums` part), and converts the number back into true richness. 

Let me know if that doesn't make sense.
