### ISSUE TITLE
rarefaction algos

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#16]
Hey @rueuntal slogging through the code I see the following mapping for the rarefaction calculations when working with species richness (i.e., Hill number where q = 0):

```
rarefy_individual -> rareNMtests::rarefaction.individual -> vegan::rarefy
rarefy_sample_implicit -> rareNMtests::rarefaction.sample -> vegan::specaccum 
```

Do you think we want to maintain the option of using our framework on other Hill numbers besides richness? rareNMtests gives us the option of running our code on q=1 (Shannon) and q=2 (Simpson) indices as well. If you don't think we'll likely ever use these then my vote is to directly code the analytical solutions rather than depend on rareNMtests and vegan for these calculations. Their functions lose some speed by carrying out redundant checks and in one case don't allow computing of the rarefaction curve for a sub sample of.all quadrats (I could request this change though).

**Comment by rueuntal** [comment]
Hey Dan - I couldn't recall we ever talked about applying our framework to other Hill numbers; so yes, my vote is to use the analytical solutions, if it's more efficient and not too time-consuming to code up. Thanks!

**Comment by dmcglinn** [comment]
Sounds good that's what I'll do.

Dan
