### ISSUE TITLE
nperm vs n_perm

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#160]
This may seem a little silly but it effects a lot of code so I want to make sure we agree before changing it. We have this argument which specifies the number of permutations given two different ways I'm leaning towards `nperm` over `n_perm`. Are there any votes out there for one over another. Felix seems to prefer `n_perm`.

**Comment by rueuntal** [comment]
Thanks for ironing out the small things @dmcglinn ! I'd vote for `nperm` for conciseness but it's not a strong preference.

**Comment by dmcglinn** [comment]
I went with `n_perm` because after looking at it every one of our object names has a `_` separating words so `n_perm` seems the most expected value from a user perspective.
