### ISSUE TITLE
is there a need for a permutation based individual-based rarefaction curve?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#167]
We use Hurlbert's analytical formulation for individual-based rarefaction, but I recently developed a permutation based approach in an attempt to get around a memory problem a user was encountering. It turned about the analytical formulation wasn't the problem so the permutation approach which is slower than the analytical formulation in general is not needed for the core computational results. Can you see another need for a permutation based rarefaction curves? BTW there are analytical formations for the 95% CI for the curve as well so deriving those from the permutations is not a perk. 

The one potential benefit of having this permutation approach would be to provide an independent value to test our analytical formulation against. If they match then the analytical formulation is working.

**Comment by rueuntal** [comment]
Hey @dmcglinn this sounds like something that would be nice to have but maybe not super urgent. What do other thinks?

**Comment by dmcglinn** [comment]
Yea I already have the method coded up so I may just provide it as a non-user facing function so that we have it for testing purposes.

**Comment by rueuntal** [comment]
Sounds great, thanks Dan!
