### ISSUE TITLE
Formulation of PIE?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#17]
Hey @rueuntal take a look here: 

https://github.com/MoBiodiv/mobr/blob/master/R/mobr.R#L256-L257

where you formulated PIE. I'm curious why the term N / (N - 1) is needed? You calculated the probability of a heterospecific (under an assumption of replacement) and then you multiply it by this. 

Thanks!

**Comment by rueuntal** [comment]
Sorry about the delay! This is PIE, probability of interspecific encounter. The term N/(N-1) results from finite sample size - ie., the probability of one individual belonging to species i is p_i = n_i / N, and the probability of another individual belonging to species i given the former is (n_i - 1) / (N - 1). 

Does that make sense? If not, the original formula is in Hurlbert 1971.

**Comment by dmcglinn** [comment]
Thanks!

Dan
