### ISSUE TITLE
D0.hat function is redundant with function rarefaction ?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#170]
We have the function `D0.hat` to carry out individual based rarefaction and extrapolation in the script `mobr_boxplots.R` and we have the function `rarefaction` in the script `mobr.R`. I think we can replace `D0.hat` with just calls to `rarefaction` because I don't think we need the extrapolation capability that `D0.hat` provides. @FelixMay any thoughts here.

**Comment by dmcglinn** [comment]
When the number of individuals surpasses the number of individuals in the sample we should just return the observed S. This is what the function `rarefaction` does when the argument `force` is set to TRUE.

**Comment by FelixMay** [comment]
Well and I think D0.hat differs here. It does not return observed S, but an extrapolated value, which is most likely higher than observed S. From my perspective this should be the case for comparisons of rarefied richness so I suggest keeping D0.hat

**Comment by dmcglinn** [comment]
I am wary of conflating rarefied richness and extrapolated richness. @rueuntal or @ngotelli do you have any thoughts on whether or not rarefied S should be the observed S or an extrapolated S using the Chao method when the sampling effort is larger than the number of individuals in the sample.

**Comment by ngotelli** [comment]
I am inclined to go with the extrapolation for consistency with basic sampling effects. As long as we are not extrapolating all the way out to the asymptote, the results will be fairly reliable.

**Comment by rueuntal** [comment]
Is S_rarefied still included in the boxplot analysis? If so, I'm guessing that extrapolation would have to be included?

**Comment by dmcglinn** [comment]
Thanks everyone for weighing in! I'll keep the extrapolation via the Chao1 approach but I'm going to move the extrapolation pieces of `D0.hat` into the function `rarefaction` and I'm going to remove `D0.hat`.

**Comment by FelixMay** [comment]
@dmcglinn That is fine with me. Does that help to get rid of the dependency of `iNEXT`? If so then I think it is a good idea. If we need `iNEXT` anyway you could save the programming effort.

**Comment by dmcglinn** [comment]
We don't have `iNext` as an dependency, and I've already ported into `rarefaction` so we're good to go. I'll submit the PR hopefully later today.

**Comment by FelixMay** [comment]
Hi @dmcglinn - argh, I could have known. It was me, who copy-pasted the D0.hat function from the `iNEXT` source code to `mobr`. In German we call this breastfeeding dementia - though the indirect version in my case :-)
