### ISSUE TITLE
What is the best hypothesis to test in multilevel boxplot comparisons

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#171]
In the function `get_mob_stats` we have the following lines: 
https://github.com/MoBiodiv/mobr/blob/master/R/mobr_boxplots.R#L402-L406
```r
   # Create factor with just two levels: treatment / control
   # for calculation of group-level differences
   group_bin = factor(rep("control", times = length(group_id)),
                      levels = c("control","treatment"))
   group_bin[group_id != ref_group] <- "treatment"
```
This variable `group_bin` essentially recodes any multilevel factors into a two level factor those that are the reference variable (='control') and those that are not (= 'treatment'). This is then used to compute F-values for ANOVA tests. Is this the hypothesis that we want to test with our permutation tests? It seems like the more general hypothesis of does the grouping category (and not a specific level) help to explain more variation in the response than we would expect by chance. When there are only two levels then there is no difference between the analyses I've just described, but in multilevel settings I think we actually want to test the overall grouping variable effect rather than the reference variable not reference variable effect. In the delta-curves provided by `get_delta_stats` we are limited to currently looking at pairwise 'ref' and 'not ref' kinds of comparisons so the current implementation is consistent with that.

**Comment by FelixMay** [comment]
Hi @dmcglinn, if I remember correctly this binary comparison is only relevant for the p-value calculation at the group level. I did not have an idea how to calculate a group level p-value for multiple groups. At the sample level the p-value is for an ANOVA like F-test, which refers to all groups. If somebody does not like the binary distinction at the group-level there is still the confidence interval option based on bootstrapping. Does this help?

**Comment by dmcglinn** [comment]
Thanks for the explanation. You're correct you've only implemented the binary comparison for the group and not at the sample scale. At the group level why is a different method needed? Are you concerned about degrees of freedom? I may be wrong but I don't think that is a concern in the context of a permutation test. For example if we have a balanced design with 20 samples and 4 grouping variables (5 samples per group) then we would be computing the F-value on an anova with df=2 at the pooled group scale. This may result in lower power but that is an essential part of carrying out tests across scales, as you scale up you lose replication and thus power.

**Comment by dmcglinn** [comment]
Ok I now see that you do not compute an F-value for the group level comparison simply a difference between the binary grouping variables. When computing a simple difference it is not clear how to do that between multiple groups - this is why an F-value is a more useful statistic in the multi-group setting. Also it is a pivotal statistic as Legendre and Legendre point out which means it has nice properties for using in permutation tests. Actually I think in the boxplots we should report the F value and the p-value. The F-values can be used in meta-analyses better than the p-values can be because they are a faithful normalized measurement of effect size.

**Comment by FelixMay** [comment]
Hi @dmcglinn, this is all right. But the problem is that at the group-level there is no replication within groups, i.e. there is just one value for each group. In my understanding we cannot calculate an F-value in this case, because we cannot compare within group variance to total variance (or between group variance). Therefore, we designed the permutation test, which just tells us if the difference between control and the rest (pooled) is different from zero.

**Comment by dmcglinn** [comment]
I've worked through it a bit more and I see that I was wrong and you were correct that the F-value is NA because there are no degrees of freedom because the model is entirely specified. I propose we do not use the binary grouping for multiple groups and we generalize the difference approach you have developed by computing the mean of all the possible group distances. We would like to know if the average observed differences in the biodiversity index are greater than expected by chance. In the case of only two groups this reduces to exactly the approach you have already developed which is nice. 

Specifically I proposed a change this line:
https://github.com/MoBiodiv/mobr/blob/master/R/mobr_boxplots.R#L232
```
get_group_diffs = function(...)
    ...
    # here is the old line
    summarise(delta = diff(value)) %>%
   # here is my proposed change
    summarise(delta = mean(dist(value)) %>%
    ...
```

**Comment by dmcglinn** [comment]
Also I'm working through making various changes to the `mob_boxplots.R` file so if you agree with me I'll submit this change as a PR for you to review.

**Comment by rueuntal** [comment]
Hi @dmcglinn @FelixMay - sorry for the late reply. Dan's proposal makes great sense to me conceptually. We could dive further into sensitivity analysis but I think it may not be necessary.

**Comment by dmcglinn** [comment]
Great thanks for the input @rueuntal

**Comment by FelixMay** [comment]
Hm, I am not totally sure yet. Conceptually that is fine, but what exactly does the mean difference tell us? There might still be very large differences that are averaged out. And how straightforward is it to interpret a p-value of the mean group difference? Instead we can also look at all pairwise differences, but then we get a lot of statistics of course.
The other issue is: Don't we need the binary treatment-control distinction anyway for the get-delta-stats analysis? 
Well, just thoughts. It is fine, when you convince me. And @dmcglinn , yes feel free to sent the PR for review.

**Comment by dmcglinn** [comment]
The mean distances tell you how variable the index is across the different groups. If the index is not variable at all (i.e., the groups don't explain variance in the response) then the mean distance will be small. If however each group differs strongly in the biodiversity index then mean distance will be large. 
Large differences are not averaged out because the distances are computed with the function `dist` which returns the euclidean distance (i.e., sqrt(sum((x_i - y_i)^2)) so if there are large differences in different directions the mean difference just gets larger.

**Comment by FelixMay** [comment]
@dmcglinn Sounds good and useful. Do you plan to code the mean distance calculation or do you want me to do that? What about my second concern: The consistency with the curve analysis? Which is just binary, as far as I remember?
