### ISSUE TITLE
Must comparisons in the continuous analysis be strictly pairwise?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#174]
This question ties into #171 in which it was noted that when multiple levels of a grouping factor are available in the 2-scale analysis the tests examine overall group effect rather than all possible pairwise comparisons. However, in the continuous analysis we compute all pairwise comparisons with the reference group and test those effects. I don't like that the the continous analysis is not a clear extension of the two-scale analysis so we could 1) alter the two-scale null model analyses so that they only make comparisons with respect to a reference group (rather than overall comparison) - this would result in 1 pvalue for each level of a group, or 2) add in the ability to examine and test for overall effects in the continuous scale analysis.  In this second case we could  compute for example an overall mean difference in richness (or difference in differences) between all the groups and plot that as a function of scale. We would sacrifice directionality of effects (in other words we would lose information on how particular treatments increase or decrease evenness for example bc there is no stated reference group) but averages of differences could provide an overall indication of how well the group variable can capture differences in the components of community structure.  It seems like this would just need an external function that could call `get_mob_stats` multiple times just changing the `ref_group` variable so that each level of a grouping factor is considered the reference. I would need to think about how to implement the null modeling component here correctly. @rueuntal @FelixMay @ngotelli do you think either of these options are immediately necessary or does one seem higher priority than the other?

**Comment by rueuntal** [comment]
Hey @dmcglinn maybe I'm not understanding the issue correctly - to provide an overall p-value in the continuous case, wouldn't it be a regression of S (or S_rare, etc.) against the variable of interest?

**Comment by dmcglinn** [comment]
Sorry my question wasn't clearer. I was actually only thinking about what we refer to in the code as the discrete analysis. In our manuscript, we refer to the "discrete approach" as the "continuous scale analysis" (to contrast it with the two-scale analysis). The confusion we just experienced makes me think better terminology.

**Comment by rueuntal** [comment]
It probably has more to do with me not really familiar with the two-scale analysis. Just to clarify, we have two scenarios, where there are only two groups, treatment and control, and where the treatment is a continuous variable or a gradient. And there are two components in the analysis, continuous (aka full-blown mobr) or two-scale. Are we talking about the two-scale analysis, applied to the scenario with a continuous variable?

**Comment by dmcglinn** [comment]
No,  I'm talking about the continuous-scale analysis with a discrete variable.

**Comment by rueuntal** [comment]
Ah, I see. Sorry about the confusion! Either solution sounds fine, and my feeling is that what we implement (or not implement) probably depends what empirical folks want to know under this scenario.
