### ISSUE TITLE
soft vs hard constraints for null models

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#180]
hey @rueuntal I'm working on the supplement for the methods paper and I have been going back through the code. Do you remember why we used a soft rather than a hard constraint on the observed SAD when generating the null communities to compare the observed pattern against? 

To see that we are using a soft constraint see these lines of code in the function `permute_comm` 
https://github.com/MoBiodiv/mobr/blob/master/R/mobr.R#L574-L576
```
permute_comm = function(...)
...
        sp_draws = sapply(plot_ids, function(x)
            sample(1:length(sp_freq), size=Ngroup[x], 
                   replace=T, prob=sp_freq))
...
```
So that is sampling with replacement where the likelihood of getting drawn is driven by the SAD but this is just a soft constraint because `sp_draws` will typically have fewer than S species than thus a different SAD. We use this function [here](https://github.com/MoBiodiv/mobr/blob/master/R/mobr.R#L905) to generate the null model for the N effect and [here](https://github.com/MoBiodiv/mobr/blob/master/R/mobr.R#L956) to generate the null model for the aggregation effect. 

One useful side-effect of this choice is that we can avoid using more complex (and probably slower) null models that would have fixed-fixed marginal totals. We already fix the row sums by holding plot abundance at either the observed or shuffled abundance level. If we also fixed the column sums (i.e., hard constraint on SAD) then we'd need to use one of these [complex null models](https://github.com/vegandevs/vegan/blob/master/man/commsim.Rd). 

A downside of using the soft constraint is that the null sad is systematically skewed towards higher evenness - this is probably one of the reasons why a density effect induces a weakly detected SAD effect in our sensitivity analyses.

**Comment by rueuntal** [comment]
Hi @dmcglinn - thanks for the detailed description of this issue. My recollection is that we tried the hard constraint first, but it failed to yield a reasonable error rate in the sensitivity test (I think it was for the test of SAD but am not 100% sure). 

By "weakly detected SAD effect" are you referring to the error rate in the sensitivity analysis when the SAD doesn't change? Our alpha level is 0.05, so we should expect ~750 significant tests among the 15000 tests conducted, and our numbers are pretty close on the mark in general.
