### ISSUE TITLE
Allow user to more easily compute nonspatial plot-based rarefaction curve

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#186]
Currently the function `rarefaction` allows the argument `method` to have three values: `indiv`, `samp`, or `spat`. To compute the nonspatial plot-based rarefaction the user has to understand that this is actually just an individual-based rarefaction (i.e., `method = 'indiv'`) and that effort is computed at the efforts (i.e., number of individuals in this case) that match how many plots were sampled.  I propose we either

1.  switch the behavior of `method = 'samp'` such that it computes this curve and not the sample-based spatially implicit rarefaction curve as it does currently, or 

2. add a new method called 'samp_ns' where ns references non-spatial. Maybe there is a better name. 

@rueuntal any thoughts here?

**Comment by rueuntal** [comment]
Hey @dmcglinn - thanks for catching this, I agree it could be confusing distinguishing the two types of sample-based curves. On the other hand, some users may find is useful to have the sample-based rarefaction curves in there, so I'd slightly prefer option 2.

**Comment by dmcglinn** [comment]
Sounds good, I'll try to get an PR in on this.

**Comment by dmcglinn** [comment]
It would be nice if the user could specify the curve acronym that use in the methods paper specifically: 
* sSBR = spatial sample-based rarefaction
* nsSBR = nonspatial sample-based rarefaction
* SBR = classic sample-based rarefaction 
* IBR = classic individual-based rarefaction

The term "classic" refers to the the traditional way in which these curves are defined as random samples of plots or individuals respectively.
