### ISSUE TITLE
aggregating results on the gradient

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#19]
Hey @rueuntal we discussed how `dat_plot` would be the input for a gradient method and would be identical to the pairwise case except it will now have additional columns for the continuous variables. Along these continuous variables we have several options for aggregating the rarefaction information. 
1. use the `group` variable to identify unique "sites" along the gradient compute rarefaction for each site and then place it on the gradient according to that site's mean value along the gradient
2. compute all the unique values of the gradient variable and then compute rarefaction results at each of these unique places along the gradient.
3. bin the values of the gradient and then apply the method suggested in 2.

**Comment by dmcglinn** [comment]
I think I'm leaning towards using the user defined groups as these can be more easily talyored to reflect the experimental design and thus the actual number of replicates.

**Comment by rueuntal** [comment]
Hey Dan - Sorry to get back to you this late, I forgot to put a note on this email and it got lost in my inbox. Yes, I totally agree.

**Comment by rueuntal** [comment]
I think this has already been resolved with the `group_var` vs `env_var` arguments in `get_delta_stats` by now.
