### ISSUE TITLE
'Error in -spat_cols'

### ISSUE THREAD

**Issue by dylancraven** [MoBiodiv/mobr#197]
When making a mob object:
`make_mob_in(h_comm3, h_attr,binary=FALSE, latlong=FALSE)`
where both h_comm3 and h_attr are matrices or data.frames

error message:
`Error in -spat_cols : invalid argument to unary operator`

**Comment by dmcglinn** [comment]
It looks like there is something wrong with one or both of the columns labeled `x` and `y` in `h_attr`. These must be of class `numeric`

**Comment by dmcglinn** [comment]
also just note that you can use the argument `coord_names` now to specify what columns in your attribute table specify the spatial coordinates. In other words they don't have to be named `x` and `y`.

**Comment by dylancraven** [comment]
thanks for the quick response. but i am not using any spatial attributes, just a group variable.

**Comment by dylancraven** [comment]
fixed. changed the column names to x and y...

**Comment by dylancraven** [comment]
and I also removed row.names from the community matrix
