### ISSUE TITLE
Problem when f_0 is zero

### ISSUE THREAD

**Issue by FelixMay** [MoBiodiv/mobr#198]
The function get_mob_stats crashes when the index f_0 equals zero in all samples. Then the corresponding beta-diversity (`f_0_beta`) equals always NA and the model fitting in file `mobr_boxplots.R` in line 281-283 crashes. There are several options where and how to catch the problem and I am not sure, what is best.

**Comment by dmcglinn** [comment]
I looked at this a little more and we may be able to get around some of `dplyr`'s strangeness with a `try` function: 

```
    models = div_dat %>%
             group_by(index, effort) %>%
             do(mod = try(lm(value ~ group, data = .), silent=TRUE))
      
```
but then in the next `dplyr` pipe some cleanup is needed. Also an important note to make is that the main error occurs when computing the beta statistic for a metric that is zero across all the gamma and alpha scales this results in all `NA` beta values which in turn results in these errors when attempting to extract the F-statistic. Possibly the cleanest solution is to write our own F-statistic function that returns NA if it is supplied only NA values. In other words not to use the default `lm` and `anova` functions.

**Comment by dmcglinn** [comment]
Ok I solved this problem the solution is pretty straightforward to just ask if the class of the returned object is an `lm` object. In the problem case in which all beta values are `NA`s the class is a `"try-error"`. Here's the solution: 

```r
get_F_values = function(div_dat, permute = F) {
    if (permute)
        div_dat = div_dat %>%
                  group_by(index, effort) %>%
                  mutate(group = sample(group))

    models = div_dat %>%
             group_by(index, effort) %>%
             do(mod = try(lm(value ~ group, data = .), silent=TRUE))
      
    models = models %>% 
             mutate(F_val = ifelse(class(mod) == 'lm', anova(mod)$F[1], NA)) %>%
             ungroup()
   
    
    models$F_val[!is.finite(models$F_val)] = NA
   
    return(models)
}
```
