### ISSUE TITLE
add documentation for example datasets

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#205]
This is relatively straightforward using Roxygen. I suggest we make a separate R script for documenting the datasets called `./R/mobr_data.R` where the documentation for the invasion, cattle tank, and fire datasets will be located. The documentation can be formatted like this: 
```r
#' This is data to be included in my package
#'
#' @name inv_comm
#' @docType data
#' @author My Name \email{blahblah@@roxygen.org}
#' @references \url{data_blah.com}
#' @keywords data
NULL
```
Once the script `mobr_data.R` is complete one simply needs to use `devtools::document()` to generate the relevant help files into the `man` directory. Here is a todo list that may be helpful: 

- [x] create `./R/mobr_data.R`
- [x] document each package (see examples in `?vegan::BCI` or `?vegan::dune`. 
- [x] run devtools::document() to generate the `.man` files (i.e., help files)
- [x] format and save each dataset as an `.rda` file format using the function `save` be sure to place these files in the `data` directory. It looks like I did this step earlier. 
- [x] remove the other remaining undocumented datasets and the raw files that we used to derive the community and plot attributes tables
- [x] push changes and submit a PR.

**Comment by T-Engel** [comment]
I worked through the to-do list above. @dmcglinn, could you review the PR, please?
