### ISSUE TITLE
S_n metrics: what gamma S_n are we interested in?

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#213]
The metric S_n is useful for isolating SAD effects that control for differences in density and aggregation effects as density is clearly standardized at the level n and aggregation is nullified because individuals are drawn randomly. The question arises as to what values of n to compute S_n at. Our rule of thumb has been alpha_n = [5, min(N)] and gamma_n = alpha_n * min(# of plots). From the resulting alpha_S_n and gamma_S_n we have computed beta_S_n which reflects differences in SADs and aggregation because we are now comparing SADs that were spatially constrained (at the alpha scale within a plot) versus unconstrained (gamma scale). 

In an effort to try to isolate just degree of aggregation we can compute beta_S_n when the same value of n is used at the alpha and gamma scales. If this metric is non-zero it is because the gamma and alpha scale SADs differ which should only happen if aggregation is non-random. This isn't 100% true because a random sample of a regional SAD does not result in a local SAD that is a perfect copy of the regional one but it is a step in the correct direction. The concepts paper (Chase et al. resubmitted) makes these arguments clearer if this is still confusing.

It turns out that it is relatively easy to compute beta_S_n in this new manner (i.e., at the same value of n at the alpha and gamma scales), but should we output and examine graphically S_n at the gamma scale for the alpha level n-value or are we only interested in S_n at the gamma scale for n = alpha_n * min(# of plots)?

**Comment by dmcglinn** [comment]
pinging @jmchase on this thread as well.

**Comment by sablowes** [comment]
My two cents: for the gamma scale S_n, I would retain the n = alpha_n * min(# of plots) as it tells us useful things about treatment effects at the gamma scale. I would only use the gamma scale curve rarefied to alpha scale n values for the beta_S_n metric.

**Comment by jmchase** [comment]
Yeah, I agree with Shane here.  As I mentioned in my previous email exchange with Dan, I think the gamma curve rarefied to alpha is specifically addressing the question of aggregation only by comparing the SADs at local and regional scales, with the difference of observed alpha Sn to expected from the gamma rarefaction indicating aggregation (though Dan rightly points out that it's not 100% perfect).  Otherwise, to simply compare gamma scale S_n among treatments, use the n = alpha_n * min(# of plots)

**Comment by dmcglinn** [comment]
Sounds good I've almost got this implemented in the R code, check out this potential new figure which specifies the n value on the beta panel. Does this seem clear enough? I just don't want users to think that the gamma S_n values displayed were used to compute the displayed beta_S_n. If you have ideas for how to improve please let me know: 

![s_n_plots](https://user-images.githubusercontent.com/1190381/43209330-5737f4f8-8ffa-11e8-8c05-0f111a3f3968.png)

**Comment by jmchase** [comment]
Yes, I think specifying the n value on the panel makes it clear this is what’s going on.  Looks good, thanks!
Jon
