### ISSUE TITLE
Minimal # of plots per group

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#23]
Should we specify a minimal # of plots for each group to carry out the plot-based (spatially-implicit & explicit) rarefactions? It probably doesn't make much sense to rarefy when there are only two or three plots.

**Comment by dmcglinn** [comment]
I think this would make good sense just like the minimum number of individuals boundary we are planning on enforcing. We could say a minimum of 10 plots?

**Comment by rueuntal** [comment]
I was thinking of 5 but 10 would definitely be better :) I'll add min_plots as a constant at the beginning of the script.

**Comment by dmcglinn** [comment]
well a limit of 5 would be consistent with our equally arbitrary limit of at least 5 individuals in each plot...

**Comment by rueuntal** [comment]
OK. We can always change those later if the empirical folks don't like them.

So 
```
min_ind = 5
min_plot = 5
```
