### ISSUE TITLE
Extract direction of 'effect size' (D-bar)

### ISSUE THREAD

**Issue by elslabbert** [MoBiodiv/mobr#241]
Hi there, I have a implementation question concerning the direction of the effect the 'treatment' on the different indices. 

At the moment it seems the 'direction of effect' (i.e. which treatment resulted in an increase or decrease in S/N/..., for example the invaded or uninvaded sites as in the example data), is primarily available as visual interpretation when plotting the get_mob_stats, is this the case? I was trying to figure out if the 'direction of treatment' could be easily extracted? The D-bar values are always positive, so from these I can't tell if treatment e.g. 'invaded' or 'uninvaded' is causing a positive or negative effect. Perhaps this is easy to incorporate by allowing the user to specify the reference treatment (ref_group) as one can in delta_stats? 
 
Being able to easily interpret the direction from the numeric output would be useful when applying mobr to several datasets/experimental designs and one then needs to plot the results using another format than the boxplots currently used in the package.

**Comment by dmcglinn** [comment]
Hey @elslabbert I apologize for the slow reply to this. You are correct that the delta statistic takes the absolute value of the difference so the directionality of the comparison is lost. You could extract the raw metric values from the function `get_mob_stats` function and then you could compute other effect size statistics of your own interest. Here is an example of how to do this: 

```r
library(mobr)
data(inv_comm)
data(inv_plot_attr)
inv_mob_in = make_mob_in(inv_comm, inv_plot_attr)
inv_stats = get_mob_stats(inv_mob_in, group_var = "group",
                          n_perm = 19, effort_samples = c(5,10))
# extract the alpha scale stats with 
inv_stats$samples_stats
# extract the gamma scale stats with
inv_stats$groups_stats
```

**Comment by jmchase** [comment]
Just to add to this.  Although it's all in there, I do think we need to step back a bit to make sure it's very clear and encouraged to use the mob stats can be used in any type of analyses (e.g., GLM, etc.).

**Comment by elslabbert** [comment]
Hi @dmcglinn, thanks for your response. This is what I ended up doing :), thanks.
