### ISSUE TITLE
Warning needed: Computing and plotting issues when the design is unbalanced

### ISSUE THREAD

**Issue by AlbanSagouis** [MoBiodiv/mobr#243]
While trying mobr, it is only after I reached the delta stats computation and found NAs, and then talked with Shane and Jon that I realised that datasets had to be balanced.
Early warnings would help.

**Comment by dmcglinn** [comment]
Dear @AlbanSagouis I think I have a patch that allows for unbalanced designs now. If you have a chance would you mind testing it out? To install this patch use the following R code `devtools::install_github("mobiodiv/mobr#244")`

Here's an example demonstrating that is works using a demo dataset
```r
library(mobr)
data(inv_comm)
data(inv_plot_attr)
inv_mob = make_mob_in(inv_comm, inv_plot_attr, c('x', 'y'))
table(inv_mob$env)
inv_mob2 = subset(inv_mob, subset = 25:100, type = 'integer')
table(inv_mob2$env)

inv_test = get_delta_stats(inv_mob, "group", type = 'discrete',
                            n_perm = 10)
inv_test2 = get_delta_stats(inv_mob2, "group", type = 'discrete',
                      n_perm = 10)

plot(inv_test, stat = 'b1')
plot(inv_test2, stat = 'b1')
```
Note that although this modification to the code will allow you to work with unbalanced designs that it still may not be a good idea if that treatment with more samples covers a broader spatial extent. I still need to add a warnings in that alert the user that an unbalanced design is being used and then also use the spatial coordinates to quickly compare spatial extents and alter the user of large differences.

**Comment by AlbanSagouis** [comment]
Dear @dmcglinn 

I ran your patch on the example data set and it worked great. I agree that adding a warning would be helpful and informative.
I've been trying to run the patch on our data set, the one I described in my previous message, but couldn't get the get_delta_stats() function to run on either a balanced or unbalanced data set but I believe it is not connected to the issue discussed here.

Thanks for addressing this issue,

Alban

**Comment by dmcglinn** [comment]
Hey @AlbanSagouis thanks for testing that little bit of code out. Can you please post the error messages you are seeing when you run `get_delta_stats()`? Thanks!

**Comment by AlbanSagouis** [comment]
Hi Dan,

Problem solved, I was having issues with the env_var argument you added. Maybe the `get_delta_stats()` function could have the same behaviour as it used to when `env_var` is `NULL`? Only the bottom row of plots would be available in that case.

This is what I get with a continuous `env_var`:
![image](https://user-images.githubusercontent.com/25483578/69427770-c6e4f200-0d27-11ea-84ad-21433be82da6.png)
