### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#25]
Here are lists of exceptions and warnings for the analysis. @dmcglinn feel free to expand.

Warnings:
- "Groups with less than min_plot plots will not be included in steps 2 & 3."
- "Step 3 will not be performed without spatial information."
- "Less than two groups has enough plots; steps 2 & 3 will not be performed."
- "Reference group has less than min_plot plots. Only step 1 will be performed."

**Comment by dmcglinn** [comment]
Cool I've incorporated some of these into my last pull request.

Dan
