### ISSUE TITLE
"mob" in the headlines

### ISSUE THREAD

**Issue by T-Engel** [MoBiodiv/mobr#260]
The "mob" has gotten a lot of bad press recently. Some examples:
- https://www.nytimes.com/2021/01/12/science/crowds-mob-psychology.html
- https://www.newyorker.com/news/dispatch/living-in-the-age-of-the-white-mob

I just wanted to start an open-ended discussion on whether people think we need to consider rebranding ourselves.

As a non-native English speaker, I guess I have always known the meaning of the word "mob" but I've never much thought about it, to be honest. Only after the most recent events, I am realizing the violence and hate that the term really refers to. And this makes me feel uncomfortable when I use the word for the measurement of biodiversity framework. Couldn't it be interpreted as glorifying violence? At least it is not my taste of humour if a mostly white-male group like us refers to themselves as "the mob". So, I think I will try to use the full name "Measurement of Biodiversity framework" in future or maybe "MoBiodiv".

How do you feel about this? @dmcglinn @jmchase @sablowes

**Comment by dmcglinn** [comment]
Hey @T-Engel hmm I see your point but it would be a pain to switch at this late stage of the game. If folks do want to switch then I would suggest ABC - Analysis of Biodiversity Changes.

**Comment by dmcglinn** [comment]
We didn't get too far in this discussion. I'm going to close it for now. Others can feel free to revive it if folks think it worthwhile.
