### ISSUE TITLE
Place null algos in separate functions per #29

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#30]
We should break the three null model algos out as separate functions rather than just nestled within the `get_delta_stats` function.  My reasons are 1) it will be easier to write a function for generating the null results for rarefied S only and not delta S which will need the same shuffling algos, 2) it makes it easier for other scientists to jump right to the important part (the null algos) and see how they work in a simple transparent way.

**Comment by rueuntal** [comment]
Totally agreed. But the structural changes are probably not trivial, so I'm inclined to postpone it until we are sure that the function in its current setting is running properly. What do you think?

**Comment by rueuntal** [comment]
Fixed per #77 .
