### ISSUE TITLE
group argument to get_delta_stats request (lower priority)

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#39]
Allow argument to `get_delta_stats` that allows user to supply their own grouping variable rather than simply using the default behavior of using each unique value of the `env_var`. For example if the explanatory variable is latitude and some groups of sites have the same latitude then it would be nice if the user could provide group_id so that these same latitude plots would not be mixed in the sampled based analyses.

**Comment by rueuntal** [comment]
Already done with `env_var` and `group_var`.
