### ISSUE TITLE
Sample based random swapping algo is identical to individual rarefaction

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#59]
The algorithm we devised to remove spatial within and between aggregation by shuffling individuals of each species randomly between plots of a given group type is identical to an appropriately rescaled individual based rarefaction for that same group.  This simplifies our code in the function `effect_of_N` I will try to submit a modified version of this function soon that only relies on rescaled individual based rarefaction curves rather than any unnecessary sample based curves.

**Comment by dmcglinn** [comment]
![image](https://cloud.githubusercontent.com/assets/1190381/16980307/a8cdd536-4e65-11e6-845b-21796a4b79e1.png)


The above figure was generated using a simple simulated community in which I attempted to only change N (some small SAD effects crept in as well). On the left panel there are three types of curves:

1. individual based rarefaction curve
2. a sample based rarefaction curve in which the abundance of each species is redistributed randomly across plots (i.e., this is in essence again an individual based rarefaction curve) 
3. the rescaled sample based curve using average density of the two groups.

The blue curves are for the community with higher density, the red curves are for the community with lower density. The delta S ploted in the right panel is the effect of N within each group we just need to compute the differences between these two curves to estimate the effect of N on differences between treatment richness.

**Comment by dmcglinn** [comment]
These changes have been incorporated into #60

**Comment by rueuntal** [comment]
Hey @dmcglinn - thanks for all the hard work! I'm back in US now and slowly catching up. 

Your insight makes perfect sense, I'm glad you figured it out (no more swapping needed, yay!). So I guess the effect of N comes purely from our operation of swapping Nplots with Nind (which also makes sense)?

I'll try to review your pull request tonight.
