### ISSUE TITLE
need to minimize class change delcarations

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#61]
In future version of the code let's work hard to minimize the number of class change declarations that we make in the code (e.g., calling `as.character()`) these seem to be generally unneeded and make the code very cumbersome to work through. A better approach is simply to convert all factors to strings at the beginning of the analysis need any downstream calls to group variables will be character strings which generally avoid side-effects. This isn't so much a single change to the code but a change to our coding behavior. I'm done complaining now thank you ;)

**Comment by rueuntal** [comment]
Good call! Thanks for providing a solution with the problem :)

Though I have to say that the class coercion in R is REALLY annoying.
