### ISSUE TITLE
How to scale axes

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#67]
One of the argument we allow users to specify when computing `get_delta_stats` is called `log_scale` which spaces the sampling of individuals evenly along a log scale. I propose that if the user sets this argument to `TRUE` that the downstream calls to our plotting routines use a log transformed x-axis when the number of individuals (not the number of samples) is the variable being displayed. 

Alternatively and maybe more generally another solution could be for users to just specify in the plotting routine whether they want log transforms on numbers of individuals, samples, or both. We could also provide this option for the S axis but for our visual displays we may want to stick with arithmetic scaling of S because it adds emphasis to the fact that the patterns show strong scale dependence.

**Comment by rueuntal** [comment]
Good call! I'm fine either way.

**Comment by rueuntal** [comment]
Hey @dmcglinn it seems that option 1 is already implemented. I'll close this.
