### ISSUE TITLE
Error in mob_stats() when calls ChaoSpecies{SpadeR}

### ISSUE THREAD

**Issue by valentinitnelav** [MoBiodiv/mobr#68]
Hi @dmcglinn!

I tested the script with [the new patch from yesterday](https://github.com/MoBiodiv/mobr/commit/c8d37f552623c56cec0fbcd30a3811bfb2f22a74) and I get now a different error. The error happens in function SpecAbunAce {SpadeR}.

One can reproduce the error with the following datasets and code:
**Datasets** – download rda objects [OK.rda](https://github.com/valentinitnelav/ConsvStat/blob/master/OK.rda) and [OK.env.rda](https://github.com/valentinitnelav/ConsvStat/blob/master/OK.env.rda)

**Code**
```
# load objects
load(file = "OK.rda")
load(file = "OK.env.rda")

# source mobr.R and mobr_boxplots.R from local machine
source("C:/MoB/mobr-master/mobr-master/R/mobr.R")
source("C:/MoB/mobr-master/mobr-master/R/mobr_boxplots.R")

# Make community object with mobr
OK_comm <- make_comm_obj(OK, OK.env)

# Run function for summary statistics - getting error in SpecAbunAce {SpadeR}
OK_stats <- mob_stats(OK_comm, "treatment")

Warning: In this case, it can't estimate the variance of Homogeneous estimation 
 Error in if ((sum(x == 1)/sum(x[x <= k])) == 1) { : 
  missing value where TRUE/FALSE needed 
```
The error seems to happen first time at row 9 in the OK object. There is only one species with 21 individuals.
Inside the SpecAbunAce{SpadeR} function the error is given by a division by zero in `if ((sum(x == 1)/sum(x[x <= k])) == 1)`
Note that the error is triggered inside mob_stats() when calling ChaoSpecies{SpadeR}:
`S = ChaoSpecies(comm$comm[i,], datatype = "abundance")`

Best,
Valentin

**Comment by dmcglinn** [comment]
this is already being handeled in #69 so i'm going to close this
