### ISSUE TITLE
SpadeR:::ChaoSpecies() error in boxplot function

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#69]
This error was reported to me by @valentinitnelav his original posting is [here](https://github.com/valentinitnelav/ConsvStat/issues/1)

I simply copy and pasted the text below...

---

I tested the script with the new patch from yesterday and I get now a different error. The error happens in function SpecAbunAce {SpadeR}.

One can reproduce the error with the following datasets and code:
Datasets – download rda objects OK.rda and OK.env.rda

Code
# load objects

load(file = "OK.rda")
load(file = "OK.env.rda")
# source mobr.R and mobr_boxplots.R from local machine

source("C:/MoB/mobr-master/mobr-master/R/mobr.R")
source("C:/MoB/mobr-master/mobr-master/R/mobr_boxplots.R")
# Make community object with mobr

OK_comm <- make_comm_obj(OK, OK.env)
# Run function for summary statistics - getting error in SpecAbunAce {SpadeR}

OK_stats <- mob_stats(OK_comm, "treatment")

Warning: In this case, it can't estimate the variance of Homogeneous estimation 
 Error in if ((sum(x == 1)/sum(x[x <= k])) == 1) { : 
  missing value where TRUE/FALSE needed 
The error seems to happen first time at row 9 in the OK object. There is only one species with 21 individuals.
Inside the SpecAbunAce{SpadeR} function the error is given by a division by zero in if ((sum(x == 1)/sum(x[x <= k])) == 1)
Note that the error is triggered inside mob_stats() when calling ChaoSpecies{SpadeR}:
S = ChaoSpecies(comm$comm[i,], datatype = "abundance")

Best,
Valentin

**Comment by dmcglinn** [comment]
I've also been getting some additional errors from the `SpadeR:::ChaoSpecies` function. This function is used to estimate the asymptotic size of the species pool. I'm not sure why it is giving us so much trouble because we do something similar in the null model portion of the analysis in which we generate the species pool's SAD. My feeling for the time being is that you should go in and just comment out any of the computations of extrapolated S. This was not a key interest of the working groups as we all agree that S never truely saturates - the concept is only useful in our option as a means to an ends for generating the SAD a for a pooled set of plots. @FelixMay did someone in the group encourage you to add those computations?

**Comment by rueuntal** [comment]
Is this only a problem in boxplot, not in the main function?

**Comment by dmcglinn** [comment]
yea just the boxplots

**Comment by dmcglinn** [comment]
@FelixMay wrote a function called `mob_stats` which computes a ton of useful statistics which are then fed into the boxplot function. Within that `mob_stats` function is where the trouble is.

**Comment by rueuntal** [comment]
OK I'll leave it to @FelixMay then :)

Just by reading the code I suspect the problem occurs because here Chao estimator is applied to plot-level data, while in our null test Chao's method is applied to the overall SAD lumped across all plots and all groups, which is less prone to have an extreme distribution as @valentinitnelav reported.

**Comment by dmcglinn** [comment]
Yea I think you're correct. I tried to rescue it from errors but requiring plot N be greater than 4 but likely there are other criteria that will need to be met as well. It would be nice if there was an easy way to try to compute the ChaoS for a plot and if there is no error then assign it otherwise give it an NA. Now if it hits an error the function just stops.

**Comment by rueuntal** [comment]
Hmmm do we want to remove the bit or try to fix it? If we want to fix it I can dig into Chao's paper to what they did exactly.

**Comment by dmcglinn** [comment]
I don't think that's necessary. I was thinking that this could possibly be accomplished programmatically using a function like `try`.

**Comment by rueuntal** [comment]
Sounds good.

**Comment by FelixMay** [comment]
Should be fixed with #132
