### ISSUE TITLE
Break the main analysis function into two for continuous vs discrete

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#72]
Right now there are lots of 
```
if (type == 'continuous'){}
else {}
```
in our code. I'm leaning towards breaking them into two separate functions, potentially suffering some repetition for better readability. @dmcglinn what do you think?

**Comment by dmcglinn** [comment]
This seems reasonable to me.

**Comment by rueuntal** [comment]
OK thanks for the confirmation. I'll work on it today and tomorrow.

**Comment by rueuntal** [comment]
Done in #75 .
