### ISSUE TITLE
Column names in plot_attr argument in make_comm_obj() function

### ISSUE THREAD

**Issue by valentinitnelav** [MoBiodiv/mobr#73]
Hi!
I have noticed that the column name of the environmental variable passed to `plot_attr` argument in `make_comm_obj()` function gets lost somehow. This happens when the environmental variable is a vector or factor or a data.frame with only one column.
The issue happens at line
```R
out$env = data.frame(plot_attr[ , -spat_cols])
```
Adding this line after the one above fixed the issue for me
```R 
colnames(out$env) <- colnames(plot_attr)[-spat_cols]
```
Best,
Valentin

**Comment by rueuntal** [comment]
Hi @valentinitnelav - thanks a lot for reporting the bug and providing a fix! It's now incorporated into the branch `4cur`.

**Comment by dmcglinn** [comment]
thx for reporting and fixing!
