### ISSUE TITLE
plot.mobr() and plot_9_panels() - wrong data frame name in "discrete" list of "mobr" object

### ISSUE THREAD

**Issue by valentinitnelav** [MoBiodiv/mobr#81]
Hi!

I worked today with a new dataset from Jon and I encountered some plotting errors with `plot.mobr()` and `plot_9_panels()` functions. I used the scripts from branch **4cur**.
I got errors because some objects in the plotting functions could not be  created because some object names changed in the structure of `mobr` object when most probably is created with the function `get_delta_stats()`.

I went line by line with some test objects and it seems that in `plot.mobr()` one should make the following change in line 90:

``` R
tests = c('indiv', 'N', 'agg') 
```

change to

``` R
tests = c('SAD', 'N', 'agg') 
```

The error was triggered when trying to access the `mobr` object , for example, like `mobr[[type]][[tests[i]]]`. And actually the `mobr` object, created previously with `get_delta_stats()` function, has 3 data frames in the list `discrete`: `SAD`, `N` and `agg`, but no `indiv`. Therefore, I presumed I can change `indiv` with `SAD`.

Then a similar error happened in `plot_9_panels()` function. Here at lines 1200 and 1202 I replaced `$ind` with `$SAD` in order to avoid the error:

``` R
mobr$discrete$ind[, -1] = lapply(mobr$discrete$ind[, -1], function(x)
      as.numeric(as.character(x))) 
delta_Sind = mobr$discrete$ind[which(as.character(mobr$discrete$SAD$group) == as.character(trt_group)), ]
```

I changed to

``` R
mobr$discrete$SAD[, -1] = lapply(mobr$discrete$SAD[, -1], function(x)
      as.numeric(as.character(x))) 
delta_Sind = mobr$discrete$SAD[which(as.character(mobr$discrete$SAD$group) == as.character(trt_group)), ]
```

Please let me know if my suggestions make sense.
I didn't have time to check  the function `get_delta_stats()`, but I presume that another option would be to make modifications there regarding the naming of the objects.

Best,
Valentin

**Comment by rueuntal** [comment]
Hi Valentin,

Sorry about the bug! You are absolutely right about the attribute name. We were tweaking the code, but the changes were not merged into `4cur`. I just merged our latest commits, and `plot.mobr()` and `plot_9_panels()` seemed to be working now. We are now pretty confident that the main function, `get_delta_stats()`, is doing great, but there could still be bugs resulted from the later changes in other supporting functions. If you run into some other problem please let us know!

**Comment by dmcglinn** [comment]
I'm going to close this issue because it seems to be resolved.
