### ISSUE TITLE
what are the best object names

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#86]
hey @rueuntal now that the code is more or less stabilized let's spend a little bit of time thinking about what we have called things. The specific names I would like to discuss is `comm`. As I go through the code more I'll probably find other object names to add in to this thread. 

With respect to `comm`. We have a function `make_comm_obj` which takes as its input an argument `comm` and another argument `plot_attr`. This is understandably confusing - why would a function that is supposed to make a `comm` take it as input. In #84 I changed the argument `comm` to `x` which is very generic but follows the convention of the package `vegan` which I think is a good authority for how to work with site-by-species matrices. This brings up a question though. Throughout the rest of our package we refer to `comm` like objects which are really just site-by-species matrices should we change these names to `x`? Is there a better name then `x` that we can think of. Maybe the simpliest solution is to change `make_comm_obj` to something else so like `make_mob_data` or something like that. 
 
Let me know what you think.

**Comment by rueuntal** [comment]
Hey @dmcglinn - good call! I have no objection changing the input of `make_comm_obj` to `x`, the old syntax was indeed confusing. For the rest of the code (e.g. in `get_delta_stats`) I think (at least sometimes) `comm` refers to the `comm` object made by `make_comm_obj`, which is site by species matrix + environment measurements + spatial coordinates. If possible I'm leaning towards keeping a meaningful name for it, if not `comm`. What do you think?

**Comment by dmcglinn** [comment]
I can see a couple of ways forward: 

1) Use the name 'comm' only when it refers to a site-by-species matrix. The site-by-species matrix is what we think of when someone says "community data". So what do you call the object that has a `comm` and other plot attributes combined? Here are a few potential names: `mob_data`,  `mob_input`, `comm_env`.

2) Use the name `spdat` to refer to site-by-species matrix, and `plotdat` to refer to the plot attributes table, and `comm` to refer to the combination of `spdat` and `plotdat` into one object.

Let me know what you think.

**Comment by rueuntal** [comment]
I'm fine either way. If #1 is more in line with the convention let's go
with that.
