### ISSUE TITLE
Add package dependancy

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#87]
quadprog

**Comment by dmcglinn** [comment]
Also add package `rgl` which is used by the function `plotSNpie`. I can see that on my server which is a "headless" machine I have some trouble installing `rgl` which means we may want either a more general solution to `rgl` such as suggested here: http://stackoverflow.com/questions/37521259/using-rgl-with-headless-display or some method way of keeping the function unchanged and just printing a warning that it doesn't work on headless machines. I'm leaning towards the latter option which requires less work.

**Comment by dmcglinn** [comment]
the specific function the `rgl` package needs is `plot3d`. Also the function `plotSADs` needs `scales::alpha` for setting transparent colors

**Comment by dmcglinn** [comment]
I think `rgl` and `scales` should be listed as "Suggests" rather than "Depends" in the description file and therefore will not be installed when `mobr` is installed because they are such fringe cases and at least `rgl` will cause trouble on headless machines.

**Comment by dmcglinn** [comment]
I can no longer seem to remember where in the package `quadprog` is needed this package only has two functions: `solve.QP`  and `solve.QP.compact`. I don't think we use either of these so maybe I made a mistake @rueuntal does this ring any bells?

**Comment by rueuntal** [comment]
@dmcglinn thanks for looking into the details! What you suggested for `rgl` and `scales` sound very reasonable to me. I don't remember `quardprog` either - could it have crept in when we were testing all the different algorithms for aggregation? And I don't recall anything relying on optimization at the moment. Let's get it removed.

**Comment by dmcglinn** [comment]
After having moved several packages from the Suggests category to the Depends category many more install errors are occurring due to needed second order dependancies. Here is a list of packages that resulted in errors: `htmlwidgets`, `quadprog`, `shiny`, `munsell`, `SpadeR`, and `plotrix`. It appears `SpadeR` caused a problem because it is listed as a remote but not as a Depends.

**Comment by rueuntal** [comment]
Hey @dmcglinn - sorry I'm a bit confused, what do we need to do here?

**Comment by dmcglinn** [comment]
We need to figure out what is the best way to list these dependencies in the package description so that 1) they are installed automatically (or at least the functions are package need) and 2) they don't generate a bunch of errors. I don't know what the best way to do this is. 

Dan

**Comment by rueuntal** [comment]
Got it. Thanks.

**Comment by FelixMay** [comment]
Hi @dmcglinn,
