### ISSUE TITLE
Legend - plot_9_panels()

### ISSUE THREAD

**Issue by valentinitnelav** [MoBiodiv/mobr#88]
Hi,

Would be nice for the user to have a legend in the richness graphs produced by plot_9_panels(), indicating which color is assigned to trt_group (e.g. red) and which to ref_group (e.g. blue).

Best,
Valentin

**Comment by dmcglinn** [comment]
Thanks for feedback will do!

Dan

**Comment by dmcglinn** [comment]
I'm going to work on `plot_9_panels` and it occurred to me that from a user perspective that it would likely be better to drop this function and only have `plot.mobr` in which case you could request the 9 panel option. Right now `plot.mobr` only returns the three panels of delta-delta S. @rueuntal and @valentinitnelav how would you guys feel about that?

**Comment by rueuntal** [comment]
Sounds good to me.

**Comment by dmcglinn** [comment]
Sweet - and this means less documentation to maintain which is always good! Will be a pain to implement this fix but totally doable.

**Comment by rueuntal** [comment]
Let me know if I can share the workload!

**Comment by dmcglinn** [comment]
Thanks I'm trying to do a big push before I get totally swamped by 
grading for the rest of the week.


dan
