### ISSUE TITLE
mob output object attributes

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#90]
If the output of `get_delta_stats` has an attribute called `$type` which is either `discrete` or `continous` is there any value to nesting the data.frames for the SAD, N, and agg effects within the attribute `$discrete`? So for example here is the current structure of the output of `get_delta_stats`: 

```
Only the first five rows of any matrices are printed

$type
[1] "discrete"

$log_scale
[1] TRUE

$indiv_rare
  sample  invaded uninvaded
1      1 1.000000  1.000000
2      2 1.881711  1.607740
3      3 2.670418  2.052937
4      4 3.385225  2.426138
5      5 4.040640  2.763523
6      6 4.647746  3.079981

$sample_rare
     group sample_plot    impl_S expl_S deltaS_agg
10 invaded           1  6.737519   9.42 2.68248095
19 invaded           2 10.378372  12.10 1.72162788
29 invaded           3 13.595478  14.44 0.84452217
39 invaded           4 16.333422  16.94 0.60657842
49 invaded           5 18.753198  19.14 0.38680190
58 invaded           6 20.729451  20.76 0.03054906

$discrete
$discrete$SAD
    group effort_ind    deltaS_emp deltaS_null_low deltaS_null_median deltaS_null_high
1 invaded          1 -4.363176e-14   -6.065703e-14      -5.245804e-14    -4.180267e-14
2 invaded          2  2.739708e-01   -6.257883e-02      -7.606259e-03     4.085399e-02
3 invaded          3  6.174812e-01   -1.298121e-01      -1.663329e-02     8.763914e-02
4 invaded          4  9.590875e-01   -1.891738e-01      -2.517006e-02     1.311027e-01
5 invaded          5  1.277117e+00   -2.404404e-01      -3.283497e-02     1.700484e-01
6 invaded          6  1.567765e+00   -2.857248e-01      -3.971128e-02     2.053122e-01

$discrete$N
    group effort_sample   ddeltaS_emp ddeltaS_null_low ddeltaS_null_median ddeltaS_null_high
1 invaded             1  4.363176e-14    -8.903989e-14       -8.715251e-15      6.558365e-14
2 invaded             2 -5.611687e-01    -2.432205e-01       -9.175297e-02      4.615233e-02
3 invaded             3 -1.190207e+00    -5.589478e-01       -2.540712e-01      2.024506e-02
4 invaded             4 -1.815606e+00    -8.762102e-01       -4.132492e-01     -7.071931e-03
5 invaded             5 -2.415627e+00    -1.172861e+00       -5.484117e-01     -1.436326e-02
6 invaded             6 -2.986400e+00    -1.444538e+00       -6.567581e-01      2.155285e-03

$discrete$agg
    group effort_sample ddeltaS_emp ddeltaS_null_low ddeltaS_null_median ddeltaS_null_high
1 invaded             1    7.291876       -1.0816237           0.1018763          1.709876
2 invaded             2    9.290809       -0.4931914           0.5208086          1.650809
3 invaded             3    9.900593       -0.8054069           0.3905931          1.382593
4 invaded             4    9.859997       -0.9420026           0.4599974          1.324997
5 invaded             5    9.756374       -1.0381263           0.3063737          1.199374
6 invaded             6    9.038851       -1.2701486           0.2588514          1.458851
```

I propose that we get rid of the nesting of the effect specific dataframes within `$discrete` and I propose that we condense this down to a data.frame because effect data.frame has the same number of columns in the same order. Returning one `data.frame` is almost always preferable over a `list` of `data.frames`. We will just have to add a column for `effect_type` which will haves the values SAD, N, or agg.

**Comment by dmcglinn** [comment]
Unfortunately this change would have some painful side-effects of digging through our functions `plot_9_panels` to make the new implementation work.

**Comment by rueuntal** [comment]
Hey @dmcglinn - I don't see any problem removing `$discrete` from the output. As for the three tests, I think `$SAD` usually have different rows and cols from the other two, as the effect is evaluated at # of individuals specified by the user instead of # of plots. Personally I'd rather keep the list so that the user could look at the effect of only one factor if they choose, but that could just be me :)

**Comment by dmcglinn** [comment]
Ohh good point about the different meaning of the effort column for the `$SAD` effect. So yea if we took my suggestion and make the column names for `effort_ind` and `effort_sample` just `effort` we would have to rely on the user to make sure that they don't get these mixed up which doesn't seem smart given that this still gives members of our group trouble. Ok then I will implement just the removal of the `$discrete` level.
